name: Orquestra Vermelha
favicon: null
layout_spectrum: 0.77207
typography_spectrum: 0.71761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0021'
    - '#410000'
    - '#6b0002'
    - '#930004'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
