name: Orquestra Vermelha
favicon: null
layout_spectrum: 0.38889661873690784
typography_spectrum: 0.5282837823033333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4205273075494915
  lightness: 0.44624031404964626
  saturation: 0.0949491267092526
  rhythmicContrast: 0.6179303403478116
purpose: []
